from collections.abc import Callable

class LED:
    def __init__(self, pin: int) -> None: ...
    def on(self) -> None: ...
    def off(self) -> None: ...
    def toggle(self) -> None: ...
    def blink(
        self, on_time: float = ..., off_time: float = ..., n: int | None = ..., background: bool = ...
    ) -> None: ...
    def close(self) -> None: ...

class OutputDevice:
    def __init__(self, pin: int, *, active_high: bool = ..., initial_value: bool = ...) -> None: ...
    def on(self) -> None: ...
    def off(self) -> None: ...
    def close(self) -> None: ...

class InputDevice:
    def __init__(self, pin: int, *, pull_up: bool | None = ...) -> None: ...
    @property
    def value(self) -> int: ...
    def close(self) -> None: ...

class Button:
    when_pressed: Callable[[], None] | None
    when_released: Callable[[], None] | None
    def __init__(
        self, pin: int, *, pull_up: bool | None = ..., bounce_time: float | None = ...
    ) -> None: ...
    def wait_for_press(self, timeout: float | None = ...) -> None: ...
    def close(self) -> None: ...
    @property
    def is_pressed(self) -> bool: ...
